// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pentasharp.Data;

#nullable disable

namespace pentasharp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pentasharp.Models.Entities.BusCompany", b =>
            {
                b.Property<int>("BusCompanyId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusCompanyId"));

                b.Property<string>("CompanyName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ContactInfo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("BusCompanyId");

                b.ToTable("BusCompanies");
            });

            modelBuilder.Entity("pentasharp.Models.Entities.Notifications", b =>
            {
                b.Property<int>("NotificationId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                b.Property<int>("BookingId")
                    .HasColumnType("int");

                b.Property<string>("Message")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTime>("SentAt")
                    .HasColumnType("datetime2");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("NotificationId");

                b.HasIndex("BookingId");

                b.HasIndex("UserId");

                b.ToTable("Notifications");
            });

            modelBuilder.Entity("pentasharp.Models.Entities.Buses", b =>
            {
                b.Property<int>("BusId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"));

                b.Property<int>("BusCompanyId")
                    .HasColumnType("int");

                b.Property<int>("BusNumber")
                    .HasColumnType("int");

                b.Property<int>("Capacity")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("BusId");

                b.HasIndex("BusCompanyId");

                b.ToTable("Buses");
            });

            modelBuilder.Entity("pentasharp.Models.Entities.Taxi", b =>
            {
                b.Property<int>("TaxiId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxiId"));

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("DriverName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("LicensePlate")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<int>("TaxiCompanyId")
                    .HasColumnType("int");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("TaxiId");

                b.HasIndex("LicensePlate")
                    .IsUnique();

                b.HasIndex("TaxiCompanyId");

                b.ToTable("Taxis");
            });

            modelBuilder.Entity("pentasharp.Models.Entities.TaxiBookings", b =>
            {
                b.Property<int>("BookingId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                b.Property<DateTime>("BookingTime")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("DropoffLocation")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Fare")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PickupLocation")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<int>("TaxiId")
                    .HasColumnType("int");

                b.Property<DateTime>("TripEndTime")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("TripStartTime")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("BookingId");

                b.HasIndex("TaxiId");

                b.HasIndex("UserId");

                b.ToTable("TaxiBookings");
            });

            modelBuilder.Entity("pentasharp.Models.Entities.BusCompany", b =>
            {
                b.Navigation("Buses");
            });

            modelBuilder.Entity("pentasharp.Models.Entities.TaxiBookings", b =>
            {
                b.Navigation("Notifications");
            });

            modelBuilder.Entity("pentasharp.Models.Entities.User", b =>
            {
                b.Navigation("Notifications");

                b.Navigation("TaxiBookings");
            });
#pragma warning restore 612, 618
        }
    }
}
