version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123  # Ensure to use a strong password
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
